import { TMenu } from '#utils/database/models/menu';

/* eslint-disable max-len */
const savouries = [
	{
		name: 'Bhuna Chicken Puff',
		description: 'A spiced & flavourful bhuna chicken filling encased in a puff pastry with a topping of black sesame seeds. Serving size (g/ml) - 85g/390kcal. Allergen - Contains Milk, Wheat, Soy, Rye, Oat, Egg. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Savouries',
		price: 190,
		foodType: 'extra-spicy',
		veg: 'non-veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/124/3c99abd0beafe902d89913741a963124.jpg',
	},
	{
		name: 'Creamy Spinach & Corn Pocket',
		description: 'Crispy Tortilla Chips loaded with peri peri cheesy dip, spicy tomato salsa & cream cheese. Share with your friends loaded with delightful dip. Serving size (g/ml) - 180g/498kcal. Allergen - Contains Milk, Wheat, Soy. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Savouries',
		price: 260,
		foodType: 'spicy',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/124/3c99abd0beafe902d89913741a963124.jpg',
	},
	{
		name: 'Malabari Egg Croissant',
		description: 'A South Indian Malabari inspired spiced egg filling with hints of coconut encased in a croissant with sesame seeds on top. Serving size (g/ml) - 180g/591kcal. Allergen - Contains Wheat, Milk, Egg. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Savouries',
		price: 265,
		foodType: 'spicy',
		veg: 'non-veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/6e2/1e76fd2396c5be2cc13842e9eb56b6e2.jpg',
	},
	{
		name: 'Classic Cinnamon Swirl',
		description: 'A classic croissant based cinnamon roll. Contains - Milk, Wheat 80 g | 424 kcal An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Savouries',
		price: 215,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/85f/bf357a6a0ed1d0c1f4be9613be41285f.jpg',
	},
];

const sandwiches = [
	{
		name: 'Chilli Paneer in Herbed Bun',
		description: 'A tangy chilli paneer filling topped with sliced cheese in a herbed bun. Serving size (g/ml) - 160g/598kcal. Allergen - Soy, Wheat, Milk An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 275,
		foodType: 'spicy',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/ad6/3cc2f43fdc1598b665cbff2ef39e8ad6.jpg',
	},
	{
		name: 'Chilly Chicken in English Muffin',
		description: 'A chilly chicken filling on a bed of chopped spinach topped with omelette & cheese in an English style muffin. Serving size (g/ml) - 160g/529kcal. Allergen - Contains Soy, Wheat, Milk, Egg. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 275,
		foodType: 'extra-spicy',
		veg: 'non-veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/834/d1e57e07b0972571f403e8d25221e834.jpg',
	},
	{
		name: 'Double Egg Bagel',
		description: 'A melange of eggs cooked two ways - scrambled and boiled. With parsley and cheese in a bagel. Contains - Wheat, Milk, Egg, Soy 185 g | 640 kcal An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 275,
		foodType: 'spicy',
		veg: 'contains-egg',
		image: 'https://b.zmtcdn.com/data/dish_photos/fa7/339dadff6042d96ab0894f9ebab73fa7.jpg',
	},
	{
		name: 'Baked Veggie Bagel',
		description: 'Herb roasted farm fresh vegetables cooked in a tomato based sauce and sandwiched in a sunflower seed and paprika bagel. Contains - Wheat, Milk, Soy 170 g | 419 kcal An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 265,
		foodType: 'spicy',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/cc9/558a09a7dbe2ba3a16cd6a2906f80cc9.jpg',
	},
	{
		name: 'Herbed Chicken Focaccia Sandwich',
		description: 'Freshly Assembled Sandwich A western styled chicken salad sandwiched in a focaccia bread. Serving size (g/ml) - 230g/717kcal Allergen - Contains Milk, Wheat An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 400,
		foodType: 'spicy',
		veg: 'non-veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/027/992096c4b694a779867a6f4c41c16027.jpg',
	},
	{
		name: 'Rayalaseema Mutton Bun Bom',
		description: 'Minced mutton wrapped in a blend of spices and herbs, stuffed in a dough bun and sprinkled with chili flakes. Serving size (g/ml) - 120g/236kcal Allergen - Contains Wheat, Soy, Rye, Oat An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 370,
		foodType: 'extra-spicy',
		veg: 'non-veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/76c/15b01ce4f84b6cc3c3a302171724b76c.jpg',
	},
	{
		name: 'Podi Cream Cheese Bagel',
		description: 'Gunpowder and cream cheese with coriander, in a sesame and poppy bagel. Contains - Wheat, Milk 150 g | 545 kcal An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 290,
		foodType: 'spicy',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/80f/7c5a5d3d5b3d2009b0b4c5c3e579980f.jpg',
	},
	{
		name: 'Chilli Cheese Toast',
		description: 'Cheesy and fiery snack on a toasted French-style baguette, topped with red, yellow and green pepper and chopped green chilli. 2 pieces per portion. Serving size (g/ml) - 140g/479kcal. Allergen - Contains Wheat, Milk, Soy, Rye, Oat An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Sandwiches',
		price: 335,
		foodType: 'spicy',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/224/72d8311ac79219f8968f4e4b405f0224.jpg',
	},
];

const wraps = [
	{
		name: 'Murgh Kathi Wrap',
		description: 'Spicy melange of chicken, onion, peppers and cheddar cheese packed in a tortilla wrap. Serving size (g/ml) - 180g/398.9kcal Allergen - Contains Wheat, Milk, Soy, Nut An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Wraps',
		price: 340,
		foodType: 'spicy',
		veg: 'non-veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/da6/c04c82806e654ca0c358a1ce33463da6.jpg',
	},
	{
		name: 'Chatpata Paratha Wrap',
		description: 'Tangy paneer and vegetable filling wrapped in spinach paratha. Serving size (g/ml) - 180g/465kcal. Allergen - Contains Wheat, Milk, Soy, Nut An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Wraps',
		price: 330,
		foodType: 'spicy',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/9ab/cfa9373790b5cb34bee6488a65a2c9ab.jpg',
	},
];

const desserts = [
	{
		name: 'Chocolate Brownie Cupcake',
		description: 'A gooey and fudgy walnut brownie loaded with chocolate. 2 pieces per portion. Serving size (g/ml) - 80g/416kcal. Allergen - Soy, Wheat, Milk, Nut. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Desserts',
		price: 280,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/522/d6a7a8887b303e5000b22a44b510a522.jpg',
	},
	{
		name: 'Blueberry Muffin',
		description: 'Buttery vanilla cake with blueberries dusted with granulated sugar for a delightfully crunchy texture. Serving size (g/ml) - 120g/376kcal. Allergen - Contains Wheat, Milk, Egg. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Desserts',
		price: 295,
		foodType: 'sweet',
		veg: 'non-veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/ea6/4e399d9520fea6ae652fe41ffbcbcea6.jpg',
	},
	{
		name: 'Double Chocolate Chip Cookie',
		description: 'A soft & chewy chocolate cookie topped with chocolate chips for the perfect textured bite Serving size (g/ml) - 80g/385kcal. Allergen - Contains Wheat, Milk, Soy. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Desserts',
		price: 270,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/845/34801fae8b500b19a86e0bec0b2ea845.jpg',
	},
	{
		name: 'Almond Butterscotch Cookie',
		description: 'A buttery cookie with a combination of crunchy almond and butterscotch. Serving size (g/ml) - 85g/370kcal. Allergen - Contains Wheat, Milk, Nut. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Desserts',
		price: 280,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/6eb/bb2621922c66e3373bedb76a9b6bb6eb.jpg',
	},
];

const frappuccino = [
	{
		name: 'Coffee Frappuccino',
		description: 'Coffee meets milk and ice in a blender and together they create one of our original Frappuccino® beverages. Energy - Tall (354ml) - 208.6 kcal / Grande (473ml) - 306.87 kcal / Venti (591ml) 391.98 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 270,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/15f/f43e4676fbf1e1519a18d93e3340e15f.jpg',
	},
	{
		name: 'Java Chip Frappuccino',
		description: 'We blend mocha sauce and Frappuccino chips with Frappuccino roast coffee and milk and ice, then top with whipped cream and mocha drizzle to bring you endless java joy. Energy - Tall (354ml) - 391.7 kcal / Grande (473ml) - 536.19 kcal / Venti (591ml) 667.4 kcal. Allergen - Contains Wheat, Milk, Soy. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 295,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/79d/28ce00688861423b99ac813b0cd6979d.jpg',
	},
	{
		name: 'Mocha Frappuccino',
		description: 'Coffee with rich mocha sauce blended with milk and ice. Topped with sweetened whipped cream. Energy - Tall (354ml) - 341.7 kcal / Grande (473ml) - 470.31 kcal / Venti (591ml) 585.42 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 315,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/ab6/8eb2e241b251c934aa5c4f9f9fb9eab6.jpg',
	},
	{
		name: 'Vanilla Cream Frappuccino',
		description: 'This rich and creamy blend of vanilla, milk and ice topped with whipped cream takes vanilla flavour to another level. Energy - Tall (354ml) - 345.1 kcal / Grande (473ml) - 474.75 kcal / Venti (591ml) 591.72 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 310,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/649/8d3ca9daffd3c744a8414e0541a86649.jpg',
	},
	{
		name: 'Espresso Frappuccino',
		description: 'Coffee is combined with a shot of espresso and milk, then blended with ice to give you a nice little jolt and lots of sipping joy. Energy - Tall (354ml) - 194.8 kcal / Grande (473ml) - 292.78 kcal / Venti (591ml) 378.2 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 310,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/85b/a7002f0f1dec1b2b6609e0bf319a985b.jpg',
	},
	{
		name: 'Caramel Frappuccino',
		description: 'A blend of coffee, sweet caramel syrup, milk and ice topped with whipped cream and a swirl of caramel drizzle. Energy - Tall (354ml) - 364.5 kcal / Grande (473ml) - 485.42 kcal / Venti (591ml) 601.65 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 305,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/d97/6b7398272b414b14f6d9781d3591bd97.jpg',
	},
	{
		name: 'Strawberries & Crème Frappuccino',
		description: 'Strawberries and milk are blended with ice and topped with a swirl of whipped cream. Energy - Tall (354ml) - 530.2 kcal / Grande (473ml) - 752.87 kcal / Venti (591ml) 962.58 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 310,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/0ed/d52a1e25668b677a0b70783ce4a280ed.jpg',
	},
	{
		name: 'White Mocha Frappuccino',
		description: 'White chocolate Frappuccino is a blend of coffee, white chocolate sauce, milk and ice. Topped with sweetened whipped cream. Energy - Tall (354ml) - 370.7 kcal / Grande (473ml) - 538.87 kcal / Venti (591ml) 643.58 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 320,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/a4f/69de9688cfc5f42335f387cdc40dca4f.jpg',
	},
	{
		name: 'Caramel Java Chip Frappuccino',
		description: 'Coffee with rich mocha flavoured sauce blended with milk chocolaty chips, caramel syrup and ice. Topped with sweetened whipped cream and chocolate drizzle. Energy - Tall (354ml) - 398 kcal / Grande (473ml) - 574.16 kcal / Venti (591ml) 714.18 kcal. Allergen - Contains Wheat, Milk, Soy. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 350,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/cd9/1b03634c382e33cc4a317ae45530bcd9.jpg',
	},
	{
		name: 'Double Chocolate Chip Frappuccino',
		description: 'Rich mocha-flavoured sauce meets up with chocolaty chips, milk and ice. Top it off with sweetened whipped cream and mocha drizzle for a real party in your mouth. Energy - Tall (354ml) - 414.9 kcal / Grande (473ml) - 580.35 kcal / Venti (591ml) 729.42 kcal. Allergen - Contains Wheat, Milk, Soy. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Frappuccino',
		price: 340,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/f3e/4c1aa6815041dae49e6d5229564a8f3e.jpg',
	},
];

const coldBeverages = [
	{
		name: 'Iced Caffè Americano',
		description: 'Espresso shots are topped with water to produce a light layer of crema, then served over ice. Energy Nil, Allergen Nil. Serving size Tall (354ml) / Grande (473ml) / Venti (591ml).',
		category: 'Cold Beverages',
		price: 250,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/f4e/ef392346623dc465eb3107d7502bbf4e.jpg',
	},
	{
		name: 'Cold Brew Black',
		description: 'Starbucks Kenya coffee is freshly ground and then steeped for 48 hours. This artisanal process results in deliciously iced coffee that is served over ice, unsweetened. Energy - Nil , Allergen - Nil An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 315,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/6da/f088c72f90fecc62b5e139d60d8306da.jpg',
	},
	{
		name: 'Iced Caffè Latte',
		description: 'Our dark, rich espresso balanced with milk. Our Iced Latte turns your favourite morning beverage into a refreshing drink that you can enjoy at any time of the day. Energy - Iced - Tall (354ml) - 121.59 kcal / Grande (473ml) - 157.5 kcal / Venti (591ml) - 176.4 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 255,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/057/32632f33976aede26beb407156b51057.jpg',
	},
	{
		name: 'Vanilla Sweet Cream Cold Brew',
		description: 'Cold brew with Vanilla Sweet Cream is made with Starbucks cold brew over ice and topped with a house made vanilla sweet cream, which floats on top of the beverage before slowly cascading down. Energy - Tall (354ml) - 63 kcal / Grande (473ml) - 84 kcal / Venti (591ml) 104.97 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 365,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/5f8/820837b19ee3ff7d36c7fb46762945f8.jpg',
	},
	{
		name: 'Iced Shaken Hibiscus & Passion Lemonade',
		description: 'Our blend of hibiscus, lemongrass and apple is slightly sweetened and hand shaken with ice for a refreshing vibrant flavour. Energy - Tall: 354 ML, 74 kcal, Grande: 473 ML, 111 kcal, Venti: 591 ML, 149 kcal. An average active adult requires 2000 kcal energy per day; however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 280,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/765/a026cde305e62d6fb50195c7d6152765.jpg',
	},
	{
		name: 'White mocha caramel Cold Brew',
		description: 'Our slow steeped Cold brew shaken with milk and white chocolate to strike the perfect balance of coffee and sweetness. Energy - Tall (354ml) - 193.6 kcal / Grande (473ml) - 288.85 kcal / Venti (591ml) 371.65 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 385,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/823/07be218766a028d6df2456ce5e873823.jpg',
	},
	{
		name: 'Iced Caramel Macchiato',
		description: 'Sweet. Creamy. And chilled to perfection. Rich espresso, milk and vanilla syrup are topped with caramel for a delightfully refreshing start to your day. Energy - Iced - Tall (354ml) - 209.59 kcal / Grande (473ml) - 287 kcal / Venti (591ml) - 325.36 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 335,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/059/8c022e30f7482347c6a7248c366d2059.jpg',
	},
	{
		name: 'Cold Coffee',
		description: 'Our signature rich in flavour espresso blended with delicate vanilla flavour and milk to create a perfect cold coffee delight. An all time favourite. Allergen - Contains Milk, Tall: 354 ML, 354 kcal, Grande: 473 ML, 473 kcal, Venti: 591 ML, 501 kcal.An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 280,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/15f/f43e4676fbf1e1519a18d93e3340e15f.jpg',
	},
	{
		name: 'Chocolate Milkshake',
		description: 'Our Starbucks signature chocolate perfected for you as a smooth and delightful milkshake. Happiness in every sip. Energy - Tall (354ml) - 632 kcal / Grande (473ml) - 825 kcal / Venti (591ml) 1050 kcal. Allergen - Contains Wheat, Milk, Soy. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 295,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/450/ddffd6918a67a3e5f37a7bd3c21fb450.jpg',
	},
	{
		name: 'Strawberry Milkshake',
		description: 'A Delicious milkshake for those with a sweet tooth and love our favourite berry, Strawberry. Energy - Tall (354ml) - 569 kcal / Grande (473ml) - 769 kcal / Venti (591ml) 943 kcal. Allergen - Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 295,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/a37/e7c3aad38b061ab1e09d2fa829843a37.jpg',
	},
	{
		name: 'Vanilla Milkshake',
		description: 'Your favourite Vanilla milkshake is now at Starbucks. A perfect delight for any mood. Energy - Tall (354ml) - 531 kcal / Grande (473ml) - 700 kcal / Venti (591ml) 920 kcal. Allergen - Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Cold Beverages',
		price: 295,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/adf/35e43f1e67336d6464f569dd22703adf.jpg',
	},
];

const hotBeverages = [
	{
		name: 'Filter Coffee',
		description: 'Your favourite South Indian filter coffee prepared using a blend of our medium and dark roast coffees. Unreasonably perfect. Energy - Hot - Picco (180ml) / Short (236ml) - 226 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Hot Beverages',
		price: 250,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/a70/0c685119085657406f83377693bc1a70.jpg',
	},
	{
		name: 'Masala Chai',
		description: 'Our traditional masala chai with abundance of strong Indian spices and flavourful handpicked teas. Energy - Hot - Picco (180ml) - 161 kcal / Short (237ml) - 237 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Hot Beverages',
		price: 250,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/5e4/24eba55ea8ac447037d90e3aee86a5e4.jpg',
	},
	{
		name: 'Elaichi Chai',
		description: 'Our traditional chai with abundance of Cardamom and flavourful handpicked teas. Energy - Hot - Picco (180ml) - 161 kcal / Short (237ml) - 236 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Hot Beverages',
		price: 250,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/3be/b09d7eaefb1de31a585a80884c8393be.jpg',
	},
	{
		name: 'Cappuccino',
		description: 'Dark, Rich in flavour espresso lies in wait under a smoothed and stretched layer of thick foam. It\'s truly the height of our baristas\' craft. Allergen - Contains Milk, Short: 237 ML, 104 kcal, Tall: 354 ML, 104 kcal, Grande: 473 ML, 173 kcal, Venti: 591 ML, 220 kcal',
		category: 'Hot Beverages',
		price: 305,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/468/beafebeb370a02fdc9fdd1dc4ac45468.jpg',
	},
	{
		name: 'Latte',
		description: 'Our dark, Rich in flavour espresso balanced with steamed milk and a light layer of foam. A perfect coffee warm up. Allergen - Contains Milk, Short: 237 ML, 104 kcal, Tall: 354 ML, 173 kcal, Grande: 473 ML, 220 kcal, Venti: 591 ML, 289 kcal.An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Hot Beverages',
		price: 255,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/46f/879e3f36c309519bd089ce9a8d13746f.jpg',
	},
	{
		name: 'Caffe Americano',
		description: 'Rich in flavour, full-bodied espresso with hot water in true European style. Short: 237 ML, 0 kcal, Tall: 354 ML, 0 kcal, Grande: 473 ML, 0 kcal, Venti: 591 ML, 0 kcal. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Hot Beverages',
		price: 250,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/859/8ab5b36ad575355648e552f578675859.jpg',
	},
	{
		name: 'Flat White',
		description: 'Expertly steamed milk poured over shots of ristretto and finished with a Starbucks signature dot. Allergen - Contains Milk, Short: 237 ML, 104 kcal, Tall: 354 ML, 173 kcal, Grande: 473 ML, 220 kcal, Venti: 591 ML, 289 kcal',
		category: 'Hot Beverages',
		price: 285,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/c67/01ff4226b0aa37214981a61f4f330c67.jpg',
	},
	{
		name: 'Hazelnut Caffe Latte',
		description: 'Our dark, rich espresso balanced with Hazelnut flavored syrup, steamed milk and a light layer of foam. Hot - Short (237ml) - 129.8 kcal / Tall (354ml) - 199 kcal / Grande (473ml) - 246.2 kcal / Venti (591ml) 315.4 kcal Allergen - Contains Milk An average active adult requires 2000 kcal energy per day, however, calorie needs may vary."',
		category: 'Hot Beverages',
		price: 310,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/4a3/3093f65a76fafd6242aed4f36bba04a3.jpg',
	},
	{
		name: 'Vanilla Caffe Latte',
		description: 'Our dark, rich espresso balanced with vanilla flavored syrup, steamed milk and a light layer of foam. Hot - Short (237ml) - 124.8 kcal / Tall (354ml) - 194 kcal / Grande (473ml) - 241.2 kcal / Venti (591ml) 310.4 kcal Allergen - Contains Milk An average active adult requires 2000 kcal energy per day, however, calorie needs may vary."',
		category: 'Hot Beverages',
		price: 340,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/49f/b23c96e79f0aa157fb47b36b6617049f.jpg',
	},
	{
		name: 'White Chocolate Mocha',
		description: 'Our signature espresso meets white chocolate sauce and steamed milk, then is finished off with sweetened whipped cream in this white chocolate delight. Allergen - Contains Milk, Short: 237 ML, 252 kcal, Tall: 354 ML, 395 kcal, Grande: 473 ML, 451 kcal, Venti: 591 ML, 564 kcal',
		category: 'Hot Beverages',
		price: 300,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/229/163717ae27e6e3979bca0d83ff86f229.jpg',
	},
	{
		name: 'Caffe Mocha',
		description: 'We combine our Rich in flavour, full-bodied espresso with bittersweet mocha sauce and steamed milk. The classic coffee drink to satisfy your sweet tooth. Hot - Short (237ml) - 232 kcal / Tall (354ml) - 335.7 kcal / Grande (473ml) - 391.1 kcal / Venti (591ml) 472.7 kcal Allergen - Contains Milk An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Hot Beverages',
		price: 315,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/784/68079cc30be931ca6230c652b55ab784.jpg',
	},
	{
		name: 'Caramel Macchiato',
		description: 'Freshly steamed milk with vanilla-flavored syrup is marked with espresso and topped with caramel drizzle. Allergen - Contains Milk, Short: 237 ML, 162 kcal, Tall: 354 ML, 255 kcal, Grande: 473 ML, 333 kcal, Venti: 591 ML, 426 kcal',
		category: 'Hot Beverages',
		price: 335,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/b6d/66c952e81802a59401624547c5f96b6d.jpg',
	},
	{
		name: 'Signature Hot Chocolate',
		description: 'Four cocoas and fresh steamed milk topped with chocolate powder. Energy per serving size - Hot - Short (237ml) - 283.99 kcal / Tall (354ml) - 445.89 kcal / Grande (473ml) - 580.13 kcal / Venti (591ml) 735.16 kcal. Allergen - Contains Milk. An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.',
		category: 'Hot Beverages',
		price: 315,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/304/4015806a5135dedbd3f78f4b18d12304.jpg',
	},
];

const special = [
	{
		name: 'Toffee Nut Crunch Crème Frappuccino',
		description: 'Delight your senses with our Toffee Nut Crème Frappuccino. A perfect blend of milk, heartwarming flavors of buttery toffee and the warmth of toasted nuts. Topped with toffee nut whipped cream and graham crackers. A coffee free offering. Serving size (ml)/Calories (kcal) - Tall: 354 ML, 372 kcal, Grande: 431 ML, 501 kcal, Venti: 591 ML, 618 kcal Allergen - Contains Wheat, Milk, Oat.',
		category: 'Holiday Special',
		price: 460,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/23b/5ce65a25e7dae173db0921e05f79723b.jpg',
	},
	{
		name: 'Crunchy Red Hat Mocha Frappuccino',
		description: 'Almost too cute to drink, our Crunchy Red Hat Mocha Frappuccino is a perfect blend of milk, smooth coffee, decadent mocha, a generous amout of vanilla whipped cream topped with a chocolate whipped cream hat and strawberry drizzle, finished with crunchy graham crackers. This beverage is not just a delight for your eyes but also a party in your mouth. Serving size (ml)/Calories (kcal) - Tall: 354 ML, 552 kcal, Grande:431ML,755 kcal, Venti: 591ML,908kcal Allergen -Contains Wheat,Soy,Milk,Oat.',
		category: 'Holiday Special',
		price: 460,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/d7c/9d2ff92224be4fe8017c126ac2b0dd7c.jpg',
	},
	{
		name: 'Chestnut Mont Blanc Frappuccino',
		description: 'Inspired by the french dessert of the same name, our Chestnut Mont Blanc Frappuccino showcases the harmony between the earthy and nutty notes of chestnut, blended with milk and coffee with a layer of chestnut whipped cream in between. Topped with a luscious chestnut whipped cream and chestnut sauce drizzled over it. Serving size (ml)/Calories (kcal) - Tall: 354 ML, 407 kcal, Grande: 431 ML, 539 kcal, Venti: 591 ML, 572 kcal Allergen - Contains Wheat, Milk, Nut, Oat, Soy.',
		category: 'Holiday Special',
		price: 460,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/2a8/03a9cd12666aeda9d6a8f87afeea22a8.jpg',
	},
	{
		name: 'Toffee Nut Crunch Cold Brew',
		description: 'Our small-batch cold brew—slow-steeped for a super-smooth taste—gets even better. Paired with the buttery and warm notes of toffee nut foam, topped with graham crackers. Serving size (ml)/Calories (kcal) - Tall: 354 ML, 194 kcal, Grande: 431 ML, 223 kcal, Venti: 591 ML, 253 kcal Allergen - Contains Wheat, Milk, Oat.',
		category: 'Holiday Special',
		price: 435,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/eaf/b1aee818f3aacad99cf88ac92a0a3eaf.jpg',
	},
	{
		name: 'Iced Toffee Nut Crunch Latte',
		description: 'Delight your senses with our Iced Toffee Nut Crunch Latte. A perfect combination of velvety milk, our signature espresso, heartwarming flavors of buttery toffee and the warmth of toasted nuts. Topped with toffee nut whipped cream and graham crackers. Served over ice. Serving size (ml)/Calories (kcal) - Tall: 354 ML, 280 kcal, Grande: 431 ML, 341kcal, Venti: 591 ML, 393 kcal Allergen - Contains Wheat, Milk, Oat.',
		category: 'Holiday Special',
		price: 435,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/ff8/00e14b30b64965983bb1b6c0d10c0ff8.jpg',
	},
	{
		name: 'Iced Crunchy Red Hat Mocha',
		description: 'Almost too cute to drink, our Iced Crunchy Red Hat Mocha Latte combines velvety milk, our signature Espresso,decadent mocha, a generous amout of vanilla whipped cream topped with a chocolate whipped cream hat and strawberry drizzle,finished with crunchy graham crackers.This beverage is not just a delight for your eyes but also a party in your mouth. Served over ice. Serving size(ml)/Calories(kcal) -Tall:354 ML,396kcal,Grande:431ML,477kcal, Venti:591ML,545kcal Allergen-Contains Wheat,Milk,Oat.',
		category: 'Holiday Special',
		price: 435,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/98a/de94c36c8c0e7ee24f62326ad5a1b98a.jpg',
	},
	{
		name: 'Iced Chestnut Mont Blanc Latte',
		description: 'Inspired by the french dessert of the same name, our Iced Chestnut Mont Blanc Latte showcases the harmony between the earthy and nutty notes of chestnut, velvety milk, and our signature espresso. Topped with a luscious chestnut whipped cream and chestnut sauce drizzled over it. Served over ice. Serving size (ml)/Calories (kcal) - Tall: 354 ML, 312 kcal, Grande: 431 ML, 387 kcal, Venti: 591 ML, 433 kcal Allergen - Contains Wheat, Milk, Nut, Oat, Soy.',
		category: 'Holiday Special',
		price: 435,
		foodType: 'sweet',
		veg: 'veg',
		image: 'https://b.zmtcdn.com/data/dish_photos/4d6/ef3d94fa9f88d5d8b904a3b8655c64d6.jpg',
	},
];

let menus = [
	...special,
	...frappuccino,
	...coldBeverages,
	...hotBeverages,
	...savouries,
	...sandwiches,
	...wraps,
	...desserts,
] as TMenu[];

menus = menus.map((menu) => {
	menu.restaurantID = 'starbucks';
	if (!menu?.taxPercent) menu.taxPercent = 5;
	if (!menu?.hidden) menu.hidden = false;
	return menu;
});

export { menus };
